[tools]
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

[tasks."vuln:check"]
description = "Run Go vulnerability checks"
run = "govulncheck ./..."

[tasks.'mod:verify']
description = "Verify Go module dependencies"
run = "go mod verify"

[tasks.'actions:pin:check']
# Need github token to avoid rate limit
description = "Check for action pinned version"
run = "pinact run --check"

[tasks.'actions:outdated']
# Need github token to avoid rate limit
description = "Check for outdated action versions"
run = "pinact run --update --diff"
