[tools]
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

[tasks.govulncheck]
description = "Run Go vulnerability checks"
run = "govulncheck ./..."

[tasks.'mod:verify']
description = "Verify Go module dependencies"
run = "go mod verify"

[tasks.'tidy:check']
description = "Check whether Go module dependencies are tidy"
run = "go mod tidy && git diff --exit-code go.mod go.sum"

[tasks.'lint:newline:check']
description = "Check Newline Lint issues"
run = "git ls-files | xargs nllint --trim-space"
